"""Mock dataset of 30 candidate accounts for V0 pipeline validation.

This dataset is intentionally diverse:
- High ICP fit (B2B short video agencies, industrial video services)
- Medium ICP fit (marketing companies with partial overlap)
- Low/unrelated (consumer brands, personal accounts)
- Competitors (companies offering similar AI tools)
- Large enterprises with in-house R&D capability
- Small agencies / freelancers

Each entry pre-defines scoring attributes so the deterministic
BuyerScoringService produces reproducible, reasonable rankings.
"""

from ...domain.opportunity.models import AccountCandidate

MOCK_CANDIDATES: list[AccountCandidate] = [
    # ── HIGH ICP FIT: B2B short video agencies ──────────────────────────
    AccountCandidate(
        platform="douyin",
        account_name="星火短视频获客",
        profile_url="https://www.douyin.com/user/mock_xinghuo",
        bio="专注B2B企业短视频获客，服务制造业、工业品企业50+，提供短视频代运营+线索获取一体化方案",
        follower_count=12800,
        source_queries=["企业短视频获客", "B2B短视频"],
        raw_data={
            "icp_fit": 25,
            "pain_intensity": 20,
            "usage_frequency": 15,
            "existing_spend": 13,
            "customer_value": 9,
            "buy_vs_build": 9,
            "reachability": 4,
            "business_type": "b2b_short_video_agency",
            "evidence": [
                "明确提供B2B企业短视频代运营服务，客户50+",
                "每日发布制造业短视频内容，需要持续产出选题",
                "官网展示多个制造业客户案例，存在重复行业研究需求",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="工业短视频工厂",
        profile_url="https://www.douyin.com/user/mock_gongye",
        bio="机械设备/工业品短视频代运营，服务激光、机床、自动化企业，月均产出60条工业视频",
        follower_count=8900,
        source_queries=["工业品短视频", "机械设备短视频"],
        raw_data={
            "icp_fit": 24,
            "pain_intensity": 18,
            "usage_frequency": 15,
            "existing_spend": 12,
            "customer_value": 8,
            "buy_vs_build": 8,
            "reachability": 4,
            "business_type": "industrial_video_agency",
            "evidence": [
                "专注机械设备和工业品短视频，月均60条说明高频产出需求",
                "服务激光、机床等多行业，存在跨行业研究需求",
                "团队规模暗示已投入视频制作成本，有工具采购预算",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="获客引擎Pro",
        profile_url="https://www.douyin.com/user/mock_huoke",
        bio="ToB短视频营销服务商，帮企业从0做抖音账号矩阵，客户覆盖制造业、建材、化工行业",
        follower_count=23400,
        source_queries=["短视频代运营", "企业账号矩阵"],
        raw_data={
            "icp_fit": 23,
            "pain_intensity": 17,
            "usage_frequency": 14,
            "existing_spend": 14,
            "customer_value": 8,
            "buy_vs_build": 7,
            "reachability": 4,
            "business_type": "b2b_marketing_agency",
            "evidence": [
                "ToB短视频营销服务，覆盖制造业、建材、化工多行业",
                "帮企业从0做账号矩阵，说明有大量新客户需求",
                "2.3万粉丝说明自身运营能力强，可能愿意尝试新工具",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="制造业抖音运营老张",
        profile_url="https://www.douyin.com/user/mock_laozhang",
        bio="10年制造业经验，专帮工厂做抖音获客，已服务100+制造企业，提供代运营+培训",
        follower_count=45600,
        source_queries=["制造业抖音运营", "工厂短视频"],
        raw_data={
            "icp_fit": 24,
            "pain_intensity": 19,
            "usage_frequency": 13,
            "existing_spend": 11,
            "customer_value": 7,
            "buy_vs_build": 8,
            "reachability": 5,
            "business_type": "manufacturing_video_consultant",
            "evidence": [
                "服务100+制造企业，规模大，需求研究是刚需",
                "同时提供代运营+培训，说明有多个业务线需要信息输入",
                "个人IP模式但团队化运营迹象明显",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="B2B矩阵营销",
        profile_url="https://www.douyin.com/user/mock_juzhen",
        bio="专注ToB企业抖音矩阵搭建，服务机械设备、五金配件、工业自动化客户，月产出200+视频",
        follower_count=6700,
        source_queries=["企业账号矩阵", "B2B短视频"],
        raw_data={
            "icp_fit": 23,
            "pain_intensity": 16,
            "usage_frequency": 15,
            "existing_spend": 12,
            "customer_value": 7,
            "buy_vs_build": 8,
            "reachability": 3,
            "business_type": "b2b_matrix_agency",
            "evidence": [
                "月产出200+视频，高频内容需求，选题研究负担重",
                "服务多个工业细分行业，需要做大量行业调研",
                "矩阵模式说明管理多个账号，工具化需求明确",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="激光行业短视频代运营",
        profile_url="https://www.douyin.com/user/mock_jiguang",
        bio="深耕激光切割、焊接设备短视频，服务大族、IPG等上下游企业，提供从内容到获客全链路",
        follower_count=5200,
        source_queries=["机械设备短视频", "工业品短视频"],
        raw_data={
            "icp_fit": 25,
            "pain_intensity": 17,
            "usage_frequency": 13,
            "existing_spend": 10,
            "customer_value": 8,
            "buy_vs_build": 9,
            "reachability": 4,
            "business_type": "niche_industrial_agency",
            "evidence": [
                "深耕激光细分行业，服务大族、IPG上下游，客户价值高",
                "从内容到获客全链路服务，说明需要市场洞察支持",
                "细分行业研究频次高，AI工具能直接提升效率",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="企业短视频托管",
        profile_url="https://www.douyin.com/user/mock_tuoguan",
        bio="为企业提供短视频全托管服务，从账号定位到拍摄运营，已服务200+ ToB客户",
        follower_count=18300,
        source_queries=["短视频代运营", "企业短视频获客"],
        raw_data={
            "icp_fit": 22,
            "pain_intensity": 16,
            "usage_frequency": 14,
            "existing_spend": 13,
            "customer_value": 8,
            "buy_vs_build": 7,
            "reachability": 4,
            "business_type": "full_service_agency",
            "evidence": [
                "200+ ToB客户，规模大，研究需求是日常刚需",
                "全托管服务模式说明需要持续产出高质量内容",
                "已投入专业团队，有工具采购预算空间",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="工业品内容营销社",
        profile_url="https://www.douyin.com/user/mock_neirong",
        bio="专注工业品内容营销，帮机械、电气、自动化企业做内容策略+代运营，服务30+品牌",
        follower_count=9100,
        source_queries=["工业品短视频", "ToB短视频怎么找客户"],
        raw_data={
            "icp_fit": 23,
            "pain_intensity": 17,
            "usage_frequency": 12,
            "existing_spend": 11,
            "customer_value": 7,
            "buy_vs_build": 8,
            "reachability": 4,
            "business_type": "industrial_content_agency",
            "evidence": [
                "30+工业品牌客户，内容策略是核心服务",
                "覆盖机械、电气、自动化，多行业研究负担重",
                "内容策略服务需要大量市场数据支撑",
            ],
        },
    ),
    # ── MEDIUM ICP FIT: Marketing companies with partial overlap ─────────
    AccountCandidate(
        platform="douyin",
        account_name="品牌营销策划李老师",
        profile_url="https://www.douyin.com/user/mock_pinpai",
        bio="品牌营销策划师，服务企业客户，有少量短视频业务，主要做传统营销咨询",
        follower_count=34000,
        source_queries=["短视频代运营"],
        raw_data={
            "icp_fit": 12,
            "pain_intensity": 8,
            "usage_frequency": 6,
            "existing_spend": 6,
            "customer_value": 5,
            "buy_vs_build": 5,
            "reachability": 4,
            "business_type": "brand_marketing_consultant",
            "evidence": [
                "以传统营销咨询为主，短视频业务占比小",
                "企业客户基础存在，但短视频需求不明确",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="抖音探店本地生活",
        profile_url="https://www.douyin.com/user/mock_tanshi",
        bio="专注本地生活探店，帮餐饮、酒店做抖音团购和探店视频，服务本地商户300+",
        follower_count=56000,
        source_queries=["企业短视频获客"],
        raw_data={
            "icp_fit": 5,
            "pain_intensity": 6,
            "usage_frequency": 8,
            "existing_spend": 5,
            "customer_value": 3,
            "buy_vs_build": 4,
            "reachability": 3,
            "business_type": "local_life_agency",
            "evidence": [
                "专注本地生活探店，与B2B工业品不相关",
                "服务餐饮酒店，目标客户与ICP不匹配",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="电商短视频代运营",
        profile_url="https://www.douyin.com/user/mock_dianshang",
        bio="天猫淘宝商家短视频代运营，帮电商商家做产品展示视频，月均1000+条",
        follower_count=21000,
        source_queries=["短视频代运营"],
        raw_data={
            "icp_fit": 8,
            "pain_intensity": 7,
            "usage_frequency": 10,
            "existing_spend": 8,
            "customer_value": 4,
            "buy_vs_build": 5,
            "reachability": 3,
            "business_type": "ecommerce_video_agency",
            "evidence": [
                "服务电商商家为主，与B2B获客场景有差异",
                "视频量大但场景不同，目标客户不匹配",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="MCN机构官方账号",
        profile_url="https://www.douyin.com/user/mock_mcn",
        bio="签约达人孵化，泛娱乐内容为主，覆盖搞笑、剧情、颜值类达人50+",
        follower_count=89000,
        source_queries=["企业账号矩阵"],
        raw_data={
            "icp_fit": 4,
            "pain_intensity": 3,
            "usage_frequency": 5,
            "existing_spend": 4,
            "customer_value": 3,
            "buy_vs_build": 3,
            "reachability": 2,
            "business_type": "mcn_entertainment",
            "evidence": [
                "泛娱乐MCN，与企业服务完全不相关",
                "达人孵化模式与B2B获客无关",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="知识付费创业导师",
        profile_url="https://www.douyin.com/user/mock_zhishi",
        bio="创业导师，教人做抖音变现，知识付费为主，粉丝主要是个人创业者",
        follower_count=120000,
        source_queries=["ToB短视频怎么找客户"],
        raw_data={
            "icp_fit": 6,
            "pain_intensity": 4,
            "usage_frequency": 4,
            "existing_spend": 3,
            "customer_value": 2,
            "buy_vs_build": 3,
            "reachability": 2,
            "business_type": "knowledge_creator",
            "evidence": [
                "知识付费模式，目标用户是个人而非企业",
                "内容为创业方法论，非B2B服务",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="律所短视频运营",
        profile_url="https://www.douyin.com/user/mock_lvshi",
        bio="帮律所和律师做短视频获客，专注法律服务行业，已服务50+律所",
        follower_count=7800,
        source_queries=["短视频精准获客"],
        raw_data={
            "icp_fit": 10,
            "pain_intensity": 12,
            "usage_frequency": 10,
            "existing_spend": 8,
            "customer_value": 5,
            "buy_vs_build": 6,
            "reachability": 4,
            "business_type": "professional_services_agency",
            "evidence": [
                "专业服务业（律所）短视频获客，模式可迁移但行业不同",
                "50+客户说明有规模，但行业与制造业不直接相关",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="教育培训抖音运营",
        profile_url="https://www.douyin.com/user/mock_jiaoyu",
        bio="帮K12和职业教育机构做短视频招生，月均获客线索500+",
        follower_count=15600,
        source_queries=["短视频精准获客"],
        raw_data={
            "icp_fit": 7,
            "pain_intensity": 8,
            "usage_frequency": 9,
            "existing_spend": 7,
            "customer_value": 4,
            "buy_vs_build": 5,
            "reachability": 3,
            "business_type": "education_marketing",
            "evidence": [
                "教育培训行业，与B2B制造业不直接相关",
                "短视频获客模式存在，但目标客户不同",
            ],
        },
    ),
    # ── COMPETITORS: Similar AI tools / Research agents ──────────────────
    AccountCandidate(
        platform="douyin",
        account_name="AI获客智能科技",
        profile_url="https://www.douyin.com/user/mock_ai_huoke",
        bio="AI驱动的B2B获客平台，利用大模型自动挖掘企业线索，服务SaaS和科技企业",
        follower_count=11200,
        source_queries=["企业短视频获客"],
        raw_data={
            "icp_fit": 0,
            "pain_intensity": 0,
            "usage_frequency": 0,
            "existing_spend": 0,
            "customer_value": 0,
            "buy_vs_build": 0,
            "reachability": 0,
            "business_type": "competitor_ai_tools",
            "is_competitor": True,
            "evidence": [
                "已提供AI驱动的B2B获客平台，是竞品",
                "服务相似客户群体，直接竞争关系",
            ],
        },
    ),
    AccountCandidate(
        platform="douyoduo",
        account_name="竞品分析大师",
        profile_url="https://www.douyin.com/user/mock_jingpin",
        bio="提供AI市场研究和竞品分析工具，帮企业自动收集行业数据和竞品动态",
        follower_count=8400,
        source_queries=["企业短视频获客"],
        raw_data={
            "icp_fit": 0,
            "pain_intensity": 0,
            "usage_frequency": 0,
            "existing_spend": 0,
            "customer_value": 0,
            "buy_vs_build": 0,
            "reachability": 0,
            "business_type": "competitor_research_tool",
            "is_competitor": True,
            "evidence": [
                "AI市场研究和竞品分析工具，功能高度重叠",
                "目标客户群与OpportunityRadar高度重合",
            ],
        },
    ),
    # ── LARGE ENTERPRISE: In-house R&D capability ────────────────────────
    AccountCandidate(
        platform="douyin",
        account_name="某大型传媒集团官方",
        profile_url="https://www.douyin.com/user/mock_chuanmei",
        bio="旗下拥有短视频MCN、广告投放、内容营销多条业务线，员工2000+",
        follower_count=320000,
        source_queries=["企业账号矩阵", "短视频代运营"],
        raw_data={
            "icp_fit": 10,
            "pain_intensity": 5,
            "usage_frequency": 6,
            "existing_spend": 4,
            "customer_value": 3,
            "buy_vs_build": 2,
            "reachability": 1,
            "business_type": "large_media_group",
            "evidence": [
                "大型传媒集团，2000+员工，有自研能力",
                "业务线多，短视频只是其中一小部分",
                "决策链长，采购外部工具意愿低",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="某上市营销公司",
        profile_url="https://www.douyin.com/user/mock_shangshi",
        bio="A股上市营销科技公司，为客户提供数字营销全链路服务，自主研发多个营销SaaS",
        follower_count=45000,
        source_queries=["企业短视频获客", "B2B短视频"],
        raw_data={
            "icp_fit": 8,
            "pain_intensity": 4,
            "usage_frequency": 5,
            "existing_spend": 3,
            "customer_value": 2,
            "buy_vs_build": 1,
            "reachability": 1,
            "business_type": "public_marketing_company",
            "evidence": [
                "上市公司，有自研SaaS产品能力",
                "自主研发多个营销工具，buy-vs-build倾向极低",
                "规模大但采购外部小工具意愿低",
            ],
        },
    ),
    # ── SMALL AGENCIES / FREELANCERS ─────────────────────────────────────
    AccountCandidate(
        platform="douyin",
        account_name="小王说制造",
        profile_url="https://www.douyin.com/user/mock_xiaowang",
        bio="个人账号，分享制造业短视频运营技巧，偶尔接代运营单子",
        follower_count=3200,
        source_queries=["工厂短视频运营", "制造业抖音运营"],
        raw_data={
            "icp_fit": 15,
            "pain_intensity": 14,
            "usage_frequency": 8,
            "existing_spend": 2,
            "customer_value": 2,
            "buy_vs_build": 8,
            "reachability": 5,
            "business_type": "freelancer_small",
            "evidence": [
                "个人运营，有需求但预算有限",
                "制造业短视频技巧分享，说明有实际操作经验",
                "偶尔接单，说明有变现意愿但规模小",
            ],
        },
    ),
    AccountCandidate(
        account_name="三人短视频工作室",
        platform="douyin",
        profile_url="https://www.douyin.com/user/mock_sanren",
        bio="小团队短视频拍摄，主要帮本地工厂拍产品视频，团队3人",
        follower_count=1800,
        source_queries=["工厂短视频运营"],
        raw_data={
            "icp_fit": 12,
            "pain_intensity": 10,
            "usage_frequency": 6,
            "existing_spend": 1,
            "customer_value": 2,
            "buy_vs_build": 7,
            "reachability": 4,
            "business_type": "tiny_studio",
            "evidence": [
                "3人小团队，有需求但预算极为有限",
                "本地工厂拍摄，业务简单，工具需求弱",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="抖音代运营接单",
        profile_url="https://www.douyin.com/user/mock_jiedan",
        bio="接各种抖音代运营单子，个人兼职，价格优惠",
        follower_count=900,
        source_queries=["短视频代运营"],
        raw_data={
            "icp_fit": 8,
            "pain_intensity": 6,
            "usage_frequency": 4,
            "existing_spend": 1,
            "customer_value": 1,
            "buy_vs_build": 6,
            "reachability": 3,
            "business_type": "side_hustle",
            "evidence": [
                "兼职接单模式，专业度有限",
                "价格敏感，付费意愿低",
            ],
        },
    ),
    # ── MORE HIGH/MEDIUM FIT for richer ranking ──────────────────────────
    AccountCandidate(
        platform="douyin",
        account_name="自动化行业抖音服务",
        profile_url="https://www.douyin.com/user/mock_zidonghua",
        bio="专注工业自动化、PLC、变频器行业短视频，提供内容代运营+获客，服务20+自动化企业",
        follower_count=4300,
        source_queries=["工业品短视频", "机械设备短视频"],
        raw_data={
            "icp_fit": 24,
            "pain_intensity": 16,
            "usage_frequency": 12,
            "existing_spend": 10,
            "customer_value": 7,
            "buy_vs_build": 8,
            "reachability": 4,
            "business_type": "automation_industry_agency",
            "evidence": [
                "工业自动化细分，20+企业客户，客户价值高",
                "内容代运营+获客一体，需要市场研究支持",
                "细分行业深耕，研究需求高频",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="五金建材短视频",
        profile_url="https://www.douyin.com/user/mock_wujin",
        bio="帮五金建材企业做抖音，从拍片到运营，已服务40+建材厂家",
        follower_count=7200,
        source_queries=["企业短视频获客", "制造业短视频运营"],
        raw_data={
            "icp_fit": 20,
            "pain_intensity": 15,
            "usage_frequency": 11,
            "existing_spend": 9,
            "customer_value": 6,
            "buy_vs_build": 7,
            "reachability": 4,
            "business_type": "building_materials_agency",
            "evidence": [
                "40+建材厂家客户，规模中等",
                "建材行业短视频内容需求持续",
                "从拍片到运营全链路，信息输入需求大",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="化工行业内容服务",
        profile_url="https://www.douyin.com/user/mock_huagong",
        bio="化工企业短视频内容服务，帮化工企业做品牌宣传和产品展示，15家稳定客户",
        follower_count=3800,
        source_queries=["工业品短视频"],
        raw_data={
            "icp_fit": 19,
            "pain_intensity": 14,
            "usage_frequency": 10,
            "existing_spend": 8,
            "customer_value": 6,
            "buy_vs_build": 7,
            "reachability": 3,
            "business_type": "chemical_industry_agency",
            "evidence": [
                "15家稳定化工企业客户",
                "化工行业品牌宣传需求持续",
                "内容服务需要行业信息输入",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="医疗器械短视频",
        profile_url="https://www.douyin.com/user/mock_yiliao",
        bio="医疗器械行业短视频代运营，服务30+医疗器械企业，合规拍摄+内容输出",
        follower_count=11500,
        source_queries=["企业短视频获客", "B2B短视频"],
        raw_data={
            "icp_fit": 16,
            "pain_intensity": 13,
            "usage_frequency": 11,
            "existing_spend": 9,
            "customer_value": 6,
            "buy_vs_build": 7,
            "reachability": 4,
            "business_type": "medical_device_agency",
            "evidence": [
                "30+医疗器械企业客户，规模可观",
                "合规拍摄+内容输出，专业服务模式",
                "医疗器械是高价值行业，客户质量好",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="环保设备制造抖音号",
        profile_url="https://www.douyin.com/user/mock_huanbao",
        bio="环保设备制造商自己的抖音号，展示设备使用案例，自产内容",
        follower_count=6100,
        source_queries=["机械设备短视频", "工厂短视频运营"],
        raw_data={
            "icp_fit": 6,
            "pain_intensity": 5,
            "usage_frequency": 5,
            "existing_spend": 3,
            "customer_value": 2,
            "buy_vs_build": 2,
            "reachability": 3,
            "business_type": "manufacturer_self_media",
            "evidence": [
                "制造商自产内容，不是代运营服务商",
                "非服务型企业，不是目标客户",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="服装工厂抖音直播",
        profile_url="https://www.douyin.com/user/mock_fuzhuang",
        bio="服装工厂，自己做抖音直播卖货，不是代运营服务",
        follower_count=28000,
        source_queries=["工厂短视频运营"],
        raw_data={
            "icp_fit": 3,
            "pain_intensity": 4,
            "usage_frequency": 4,
            "existing_spend": 2,
            "customer_value": 2,
            "buy_vs_build": 2,
            "reachability": 3,
            "business_type": "manufacturer_own_business",
            "evidence": [
                "服装工厂自产自销，与B2B服务不相关",
                "直播卖货模式，非代运营服务商",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="武汉短视频代运营",
        profile_url="https://www.douyin.com/user/mock_wuhan",
        bio="武汉本地短视频代运营，服务本地制造企业和贸易公司，团队6人，客户20+",
        follower_count=5400,
        source_queries=["短视频代运营", "企业短视频获客"],
        raw_data={
            "icp_fit": 21,
            "pain_intensity": 15,
            "usage_frequency": 12,
            "existing_spend": 10,
            "customer_value": 7,
            "buy_vs_build": 8,
            "reachability": 4,
            "business_type": "regional_agency",
            "evidence": [
                "6人团队，20+客户，小而精的代运营团队",
                "服务本地制造企业和贸易公司，目标客户匹配",
                "团队规模说明有工具提效需求",
            ],
        },
    ),
    AccountCandidate(
        platform="douyin",
        account_name="东莞制造业抖音服务",
        profile_url="https://www.douyin.com/user/mock_dongguan",
        bio="东莞制造业短视频服务商，帮电子厂、模具厂做抖音，已服务60+工厂",
        follower_count=14200,
        source_queries=["制造业抖音运营", "工厂短视频"],
        raw_data={
            "icp_fit": 22,
            "pain_intensity": 16,
            "usage_frequency": 13,
            "existing_spend": 11,
            "customer_value": 7,
            "buy_vs_build": 8,
            "reachability": 4,
            "business_type": "regional_manufacturing_agency",
            "evidence": [
                "60+工厂客户，规模大",
                "电子厂、模具厂等制造业主战场",
                "东莞制造业密集，区域优势明显",
            ],
        },
    ),
]


def get_mock_candidates() -> list[AccountCandidate]:
    """Return a copy of the mock candidate list."""
    return list(MOCK_CANDIDATES)
