"""Domain models for research tasks and search queries."""

from __future__ import annotations

import enum
import uuid
from datetime import datetime

from pydantic import BaseModel, Field


class ResearchTaskStatus(enum.StrEnum):
    """Status of a research task through its lifecycle."""

    PENDING = "PENDING"
    PLANNING = "PLANNING"
    COLLECTING = "COLLECTING"
    FILTERING = "FILTERING"
    SCORING = "SCORING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class QueryType(enum.StrEnum):
    """Type/category of a search query."""

    DIRECT = "DIRECT"
    PAIN = "PAIN"
    SCENARIO = "SCENARIO"
    EXPANDED = "EXPANDED"


class ResearchTask(BaseModel):
    """Represents a user-initiated research task."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    goal: str
    status: ResearchTaskStatus = ResearchTaskStatus.PENDING
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    error_message: str | None = None

    def mark_status(self, status: ResearchTaskStatus) -> None:
        """Update status and refresh updated_at timestamp."""
        self.status = status
        self.updated_at = datetime.utcnow()

    def mark_failed(self, error: str) -> None:
        """Mark task as failed with error message."""
        self.status = ResearchTaskStatus.FAILED
        self.error_message = error
        self.updated_at = datetime.utcnow()


class SearchQuery(BaseModel):
    """A single search query generated by the planner."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    research_task_id: str
    query: str
    query_type: QueryType
    reason: str = ""
    status: str = "PENDING"
